version: '3.8'

services:
  postgres_user:
    image: postgres:latest
    container_name: postgres_user_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - ./user_init.sql:/docker-entrypoint-initdb.d/user_init.sql

  postgres_msg_shard0:
    image: postgres:latest
    container_name: postgres_msg_shard0_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: msg_shard0
    ports:
      - "5433:5432"
    volumes:
      - ./msg_init.sql:/docker-entrypoint-initdb.d/msg_init.sql

  postgres_msg_shard1:
    image: postgres:latest
    container_name: postgres_msg_shard1_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: msg_shard1
    ports:
      - "5434:5432"
    volumes:
      - ./msg_init.sql:/docker-entrypoint-initdb.d/msg_init.sql

  redis:
    image: redis:latest
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
